### ISSUE TITLE
Does not achieve required features

### ISSUE THREAD

**Issue by JACKYLUO1991** [PacktPublishing/Machine-Learning-with-Core-ML#2]
It does not achieve the segmentation function, so maybe something wrong with it...thanks

**Comment by joshnewnham** [comment]
Is this related to your previous submission (14 Jun)? Could you please elaborate on what is happening (or not happening).

**Comment by JACKYLUO1991** [comment]
@joshnewnham The program only displayed the real-time video capture section and did not display the segmentation result.

**Comment by joshnewnham** [comment]
Hi @actionLUO - there are a lot of places it could be failing... To help debug I've just committed a playground called SegmentationWithCoreML.playground which steps through all the man stages. Add your mov file to the *Resources* folder and update the variable *movFileName* with your filename. 

The stages are outlined and include:
// 1. Get the frames from the video
// 2. Create the masks from each frame
// 3. Extract segment from the frameAndMasks tuple array
// 4. Get dominate direction
// 5. Get candiate frames
// 6. Composite frame

At each stage; inspect the results and see if is what you're expecting. In some instances it'll be the model failing to segment the image, in other places it could be the derived heuristics used (which may require tuning).

**Comment by joshnewnham** [comment]
... I've added a test mov file to work with - attached here is some screenshots from the result of what you could be getting. The first is cropping the segment out using the segmentation as a mask and the second is the final image. 

<img width="1333" alt="screen shot 2018-07-31 at 20 17 58" src="https://user-images.githubusercontent.com/3001078/43485121-3d680a1e-9508-11e8-994a-63d3e75eed43.png">

<img width="457" alt="screen shot 2018-07-30 at 23 33 58" src="https://user-images.githubusercontent.com/3001078/43485123-3f2abbee-9508-11e8-8dad-535fa5b46a50.png">
