### ISSUE TITLE
https://colab.research.google.com/

### ISSUE THREAD

**Issue by enriqueg** [PacktPublishing/Machine-Learning-with-Core-ML#3]
I can't run any notebook in colab. 
It would be great if you adapted them to run there (GPU is free!)

**Comment by joshnewnham** [comment]
Hi @enriqueg - I can have a look into this during this week. Before doing so; could you please post the error and/or issue you are experiencing when trying to run the notebook (along with the specific notebook(s)).

**Comment by enriqueg** [comment]
Thank so much!..I figure it out, so I close this issue ! 
The problem is that you can't access external files like images etc if you don't use the Google API for Google Driver. I think it is a lot of code to change, so I will change by myself as I need it..you can skip  this for now)))..It is a great intro book to coreml! Love it, 5 stars!!
