### ISSUE TITLE
Wrong calcSimilarity example from book page 13

### ISSUE THREAD

**Issue by valeriyvan** [PacktPublishing/Machine-Learning-with-Core-ML#8]
This line is incorrect
https://github.com/PacktPublishing/Machine-Learning-with-Core-ML/blob/1626bc027d3f452deb1dc6b1699a55c0d8fe4472/Chapter01/Completed/Recommendations.playground/Contents.swift#L9

If user B hasn't watched movie watched by user A, difference is 0 which is wrong! Difference should be square of rating of user A for that movie.

But fixing this line by returning `movieRating.value * movieRating.value` will not fix this example.
Difference between users A and B should be commutative which means difference between user A and B and B and A is the same by nature.

Do that fix and calculate difference between users `sam` and `jo` and than `jo` and `sam`. Difference should be the same. But function gives different distances.

Because this implementation is fundamentally wrong.

Mapping over `userRatingsA` completely ignores movies watched by user B but not watched by user A.

**Comment by joshnewnham** [comment]
Hi @valeriyvan - thanks for highlighting and looking into it - you're right, it shouldn't return 0 where there is no match - the calculation should only be performed on the items that both users have reviewed. I have amended and committed an update and will work with @karant17 on getting the book updated (or supplementary material produced or both). 

Thanks again for your help.
